created 2 endpoints for the location service
dohyper/location.service.hyper pull request #1
Opened 2024-03-23 07:22 UTC by TooFatToKidnapp

created 2 endpoints:
/countries : lists all countries with pagination parameter, returns the countryCode. 
/countries/:countryCode: list all cities in specified country pagination parameter

2024-03-23 12:17 UTC, mathematikoi requested changes

2024-03-23 12:17 UTC, mathematikoi commented on .github/workflows/build.yaml
> +        run: "docker build -t registry.hyper.mathematikoi.agency/location.service.hyper.service.hyper:${{  github.ref_name }} ."
the name seems wrong here

2024-03-23 12:17 UTC, mathematikoi commented on .github/workflows/build.yaml
> +        run: "docker push registry.hyper.mathematikoi.agency/location.service.hyper.service.hyper:${{  github.ref_name }}"
the name seems wrong here

2024-03-23 12:17 UTC, mathematikoi commented on chart/Chart.yaml
> +name: location.service.hyper-service-hyper
the name seems wrong here

2024-03-23 12:17 UTC, mathematikoi commented on chart/templates/configmap.yaml
> +  name: {{ .Release.Name }}-location.service.hyper-service-hyper-configmap
the name seems wrong here

2024-03-23 12:17 UTC, mathematikoi commented on chart/templates/deployment.yaml
> +  name: {{ .Release.Name }}-location.service.hyper-service-hyper-deployment
the name seems wrong here

2024-03-25 08:26 UTC, TooFatToKidnapp commented
@mathematikoi if a api endpoint responds with a array of objects as one of its fields, what is the appropriate definition of the responses  properties ? should i express that the values type is a array ? or should i be more verbose and express the types of every field in the array is the case of a object?.

2024-03-25 14:41 UTC, mathematikoi commented
> @mathematikoi if a api endpoint responds with a array of objects as one of its fields, what is the appropriate definition of the responses properties ? should i express that the values type is a array ? or should i be more verbose and express the types of every field in the array is the case of a object?.

it actually depends, we need documentation to what a service should respond with.

2024-05-11 02:52 UTC, closed without merging